# 
# GitHub Actions CI/CD Pipeline
# Para proyectos ML con Python
# 

name: CI/CD Pipeline
# name: nombre del workflow que aparece en la UI de GitHub Actions

on:
  push:
    branches: [main, develop]    # Ejecuta en push a main o develop
  pull_request:
    branches: [main]             # Ejecuta en PRs hacia main
  # Permite ejecutar manualmente
  workflow_dispatch:             # Bot贸n "Run workflow" en la UI

env:
  PYTHON_VERSION: '3.10'         # Variable global: versi贸n de Python por defecto
  REGISTRY: ghcr.io              # GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }}  # Ej: usuario/repo

jobs:
  # 
  # Job 1: Lint y Formateo
  # 
  lint:
    name:  Lint & Format
    runs-on: ubuntu-latest       # Ejecuta en runner Ubuntu de GitHub
    
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4  # Clona el repositorio en el runner

      - name:  Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}  # Usa variable global
          cache: 'pip'           # Cachea dependencias pip entre runs

      - name:  Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy  # Herramientas de calidad

      - name:  Check formatting with Black
        run: black --check --diff src/ tests/  # --check: no modifica, solo verifica

      - name:  Check imports with isort
        run: isort --check-only --diff src/ tests/  # Verifica orden de imports

      - name:  Lint with flake8
        run: flake8 src/ tests/ --max-line-length=100 --statistics  # PEP8 + estad铆sticas

      - name:  Type check with mypy
        run: mypy src/ --ignore-missing-imports  # Type hints est谩ticos
        continue-on-error: true  # Opcional: no bloquear por tipos (permite warnings)

  # 
  # Job 2: Tests
  # 
  test:
    name: И Tests
    runs-on: ubuntu-latest
    needs: lint                  # Dependencia: espera a que lint termine exitosamente
    
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # Matrix: ejecuta 3 jobs en paralelo
    
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  # Cada job usa versi贸n diferente
          cache: 'pip'

      - name:  Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-xdist  # xdist: tests en paralelo

      - name: И Run tests with coverage
        run: |
          pytest tests/ -v \
            --cov=src \                # Mide coverage de src/
            --cov-report=xml \         # Reporte XML para Codecov
            --cov-report=html \        # Reporte HTML navegable
            --cov-fail-under=70 \      # Falla si coverage < 70%
            -n auto                    # -n auto: usa todos los CPUs disponibles

      - name:  Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml         # Archivo generado por pytest-cov
          fail_ci_if_error: true       # Falla si no puede subir
        if: matrix.python-version == '3.10'  # Solo sube desde una versi贸n

      - name:  Upload coverage HTML report
        uses: actions/upload-artifact@v3  # Guarda artifact descargable
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: htmlcov/               # Carpeta con reporte HTML
        if: matrix.python-version == '3.10'

  # 
  # Job 3: Build Docker
  # 
  build:
    name:  Build Docker
    runs-on: ubuntu-latest
    needs: test                  # Espera a que tests pasen antes de construir imagen
    
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Buildx: builder avanzado con cache

      - name:  Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .             # Contexto de build: directorio actual
          push: false            # Solo build, no push (es job de build, no deploy)
          tags: ${{ env.IMAGE_NAME }}:test  # Tag temporal para testing
          cache-from: type=gha   # Lee cache de GitHub Actions
          cache-to: type=gha,mode=max  # Guarda todas las capas en cache

      - name: И Test Docker image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:test python -c "print('Container OK')"
          # Smoke test: verifica que el contenedor arranca correctamente

  # 
  # Job 4: Deploy (solo en main)
  # 
  deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    permissions:
      contents: read
      packages: write

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name:  Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest

      - name:  Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name:  Notify success
        run: echo " Deploy successful! Image pushed to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

  # 
  # Job 5: ML Pipeline (opcional)
  # 
  ml-pipeline:
    name:  ML Pipeline
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'workflow_dispatch'  # Solo manual
    
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name:  Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc dvc-s3

      - name:  Pull data with DVC
        run: dvc pull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: true

      - name:  Run DVC pipeline
        run: dvc repro

      - name:  Show metrics
        run: dvc metrics show
